/go2_teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 3
    scale_linear:
      x: 0.5
      y: 0.5

    axis_angular:
      yaw: 6
    scale_angular:
      yaw: 1.0

    require_enable_button: false


/twist_mux:
  ros__parameters:
    topics:
      emergency:
        topic   : /cmd_vel_emergency
        timeout : 0.5
        priority: 255
      obstacle:
        topic   : /cmd_vel_obstacle
        timeout : 0.5
        priority: 200
      teleop:
        topic   : /cmd_vel_joy
        timeout : 0.5
        priority: 100
      nav2:
        topic   : /cmd_vel_nav
        timeout : 0.5
        priority: 10
    locks:
      e_stop_lock:
        topic   : /lock/emergency
        timeout : 0.0
        priority: 255
